version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: auth_service_db  # Base de données de production
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: myapp
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb://root:example@mongodb:27017/auth_service_db?authSource=admin
      # Autres variables d'environnement

volumes:
  mongo-data:
